"""add customer_lifetime table

Revision ID: 2590870933fe
Revises: 001_initial
Create Date: 2026-03-29 14:34:08.714742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2590870933fe'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_lifetime',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_net_revenue', sa.Float(), nullable=False),
    sa.Column('total_contribution_margin', sa.Float(), nullable=False),
    sa.Column('days_active', sa.Integer(), nullable=False),
    sa.Column('churned_day', sa.Integer(), nullable=True),
    sa.Column('predicted_clv', sa.Float(), nullable=False),
    sa.Column('actual_clv_validation_revenue', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'customer_id', name='uq_customer_lifetime_run_customer')
    )
    op.create_index(op.f('ix_customer_lifetime_customer_id'), 'customer_lifetime', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_lifetime_run_id'), 'customer_lifetime', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_lifetime_run_id'), table_name='customer_lifetime')
    op.drop_index(op.f('ix_customer_lifetime_customer_id'), table_name='customer_lifetime')
    op.drop_table('customer_lifetime')
    # ### end Alembic commands ###
